### ISSUE TITLE
imu orientation data is missing

### ISSUE THREAD

**Issue by YifeiAI** [montefiore-ai/midair-dataset#2]
Hi,

The imu data only contains linear acceleration and angular velocity. Is it possible to get orientation information? 

Also in the ground truth, what is the 'attitude' data? is it the ground truth camera orientation?

Many thanks!

**Comment by michael-fonder** [comment]
Hi,

Thank you for your interest in the dataset!

For now, the IMU dataset contains simulated measurements only for an accelerometer and a gyroscope. The 'attitude' data is the ground truth orientation of the drone (expressed with quaternions). From this information, you can compute the orientation of the camera since it is rigidly attached to the drone. Details about the sensors positioning and frames of reference can be found [here](https://midair.ulg.ac.be/tech_specs.html#sensors).
