### ISSUE TITLE
IMU data stamp

### ISSUE THREAD

**Issue by YifeiAI** [montefiore-ai/midair-dataset#3]
Hi,

I am using your dataset for visual odometry. Is the imu data captured precisely 100 hz and synchronize with images? Maybe can you share the part of the code that you recorded the imu data in airsim? Now I am having difficulties doing stable visual odometry using your dataset. 

Thank you very much!

**Comment by michael-fonder** [comment]
Hi,

Yes, IMU measurements are precisely captured at 100Hz and perfectly synchronized with the camera (the first IMU measurement is captured at the same time than the first image). We tested our data. Normally it should work fine for visual odometry. The feedback I have from [this issue](https://github.com/montefiore-ai/midair-dataset/issues/1) tends to confirm that it's working as expected.

For reasons explained in the same issue, the IMU measurements were not obtained from a straightforward Airsim export but from a simulation made on our side based on the model presented in the paper. Since the related piece of code is part of a very specific and heavily customized data generation pipeline, I cannot share it 'as is'. I've made a small toy script that implements the same model we are using for simulating IMU measurements from ground truth data. You can find it [here](https://github.com/montefiore-ai/midair-dataset/blob/master/tools/IMU-data_generator.py). Let me now if you find anything weird in it.
